import 'package:grc/features/cyber_security/sub_modules/cloud_posture/models/finding_item_model.dart';

class ComplianceFindingMappingModel {
  final String id;
  final String type;
  final FindingSeverity severity;
  final String nistCsf;
  final String cisControls;
  final String iso27001;
  final String soc2;

  const ComplianceFindingMappingModel({
    required this.id,
    required this.type,
    required this.severity,
    required this.nistCsf,
    required this.cisControls,
    required this.iso27001,
    required this.soc2,
  });

  static List<ComplianceFindingMappingModel> getMockComplianceFindings() => const [
    ComplianceFindingMappingModel(
      id: 'F-2401',
      type: 'Public Storage Bucket',
      severity: FindingSeverity.critical,
      nistCsf: 'PR.DS-1',
      cisControls: '3.4',
      iso27001: 'A.13.1.1',
      soc2: 'CC6.1',
    ),
    ComplianceFindingMappingModel(
      id: 'F-2402',
      type: 'RDP Exposed to 0.0.0.0/0',
      severity: FindingSeverity.critical,
      nistCsf: 'PR.AC-5',
      cisControls: '3.3',
      iso27001: 'A.13.1.3',
      soc2: 'CC6.6',
    ),
    ComplianceFindingMappingModel(
      id: 'F-2403',
      type: 'Root Account API Key Active',
      severity: FindingSeverity.critical,
      nistCsf: 'PR.AC-1',
      cisControls: '1.4',
      iso27001: 'A.9.2.3',
      soc2: 'CC6.3',
    ),
    ComplianceFindingMappingModel(
      id: 'F-2404',
      type: 'Database Exposed to Internet',
      severity: FindingSeverity.critical,
      nistCsf: 'PR.AC-5',
      cisControls: '3.6',
      iso27001: 'A.13.1.3',
      soc2: 'CC6.6',
    ),
    ComplianceFindingMappingModel(
      id: 'F-2405',
      type: 'Kubernetes Dashboard Exposed',
      severity: FindingSeverity.high,
      nistCsf: 'PR.AC-4',
      cisControls: '6.1',
      iso27001: 'A.9.4.1',
      soc2: 'CC6.3',
    ),
    ComplianceFindingMappingModel(
      id: 'F-2406',
      type: 'Over-privileged Service Account',
      severity: FindingSeverity.high,
      nistCsf: 'PR.AC-6',
      cisControls: '5.1',
      iso27001: 'A.9.2.5',
      soc2: 'CC6.3',
    ),
    ComplianceFindingMappingModel(
      id: 'F-2407',
      type: 'Storage Key Not Rotated (365d+)',
      severity: FindingSeverity.high,
      nistCsf: 'PR.AC-1',
      cisControls: '1.12',
      iso27001: 'A.9.2.6',
      soc2: 'CC6.3',
    ),
    ComplianceFindingMappingModel(
      id: 'F-2408',
      type: 'SSH Key Without Passphrase',
      severity: FindingSeverity.high,
      nistCsf: 'PR.AC-5',
      cisControls: '4.2',
      iso27001: 'A.9.4.3',
      soc2: 'CC6.6',
    ),
    ComplianceFindingMappingModel(
      id: 'F-2409',
      type: 'Lambda Function With Admin Role',
      severity: FindingSeverity.high,
      nistCsf: 'PR.AC-6',
      cisControls: '5.1',
      iso27001: 'A.9.2.5',
      soc2: 'CC6.3',
    ),
    ComplianceFindingMappingModel(
      id: 'F-2410',
      type: 'Bucket Encryption Disabled',
      severity: FindingSeverity.medium,
      nistCsf: 'PR.DS-1',
      cisControls: '3.4',
      iso27001: 'A.10.1.1',
      soc2: 'CC6.1',
    ),
    ComplianceFindingMappingModel(
      id: 'F-2411',
      type: 'Automated Backups Disabled',
      severity: FindingSeverity.medium,
      nistCsf: 'PR.IP-4',
      cisControls: '10.2',
      iso27001: 'A.12.3.1',
      soc2: 'A1.2',
    ),
    ComplianceFindingMappingModel(
      id: 'F-2412',
      type: 'CloudTrail Log Validation Disabled',
      severity: FindingSeverity.medium,
      nistCsf: 'DE.CM-1',
      cisControls: '8.2',
      iso27001: 'A.12.4.1',
      soc2: 'CC7.2',
    ),
    ComplianceFindingMappingModel(
      id: 'F-2413',
      type: 'Inbound HTTP (80) from Any Source',
      severity: FindingSeverity.medium,
      nistCsf: 'PR.AC-5',
      cisControls: '3.3',
      iso27001: 'A.13.1.3',
      soc2: 'CC6.6',
    ),
    ComplianceFindingMappingModel(
      id: 'F-2414',
      type: 'Firewall Rule Allows All Egress',
      severity: FindingSeverity.medium,
      nistCsf: 'PR.AC-5',
      cisControls: '12.4',
      iso27001: 'A.13.1.3',
      soc2: 'CC6.6',
    ),
    ComplianceFindingMappingModel(
      id: 'F-2415',
      type: 'IAM User Without MFA',
      severity: FindingSeverity.medium,
      nistCsf: 'PR.AC-7',
      cisControls: '6.3',
      iso27001: 'A.9.4.2',
      soc2: 'CC6.1',
    ),
    ComplianceFindingMappingModel(
      id: 'F-2416',
      type: 'Public IP, No WAF Coverage',
      severity: FindingSeverity.low,
      nistCsf: 'DE.CM-1',
      cisControls: '3.11',
      iso27001: 'A.13.1.1',
      soc2: 'CC6.6',
    ),
    ComplianceFindingMappingModel(
      id: 'F-2417',
      type: 'Lifecycle Policy Not Configured',
      severity: FindingSeverity.low,
      nistCsf: 'PR.DS-3',
      cisControls: '14.7',
      iso27001: 'A.11.2.7',
      soc2: 'CC6.5',
    ),
    ComplianceFindingMappingModel(
      id: 'F-2418',
      type: 'Key Vault Soft Delete Disabled',
      severity: FindingSeverity.low,
      nistCsf: 'PR.DS-1',
      cisControls: '10.4',
      iso27001: 'A.10.1.1',
      soc2: 'CC6.1',
    ),
    ComplianceFindingMappingModel(
      id: 'F-2419',
      type: 'No Alarm for Root Login Activity',
      severity: FindingSeverity.low,
      nistCsf: 'DE.CM-1',
      cisControls: '8.5',
      iso27001: 'A.12.4.2',
      soc2: 'CC7.2',
    ),
    ComplianceFindingMappingModel(
      id: 'F-2420',
      type: 'VPC Flow Logs Disabled (Dev VPC)',
      severity: FindingSeverity.low,
      nistCsf: 'DE.CM-1',
      cisControls: '13.6',
      iso27001: 'A.12.4.1',
      soc2: 'CC7.2',
    ),
  ];
}
