import '../../models/employee_compensation_table_row_data.dart';

class EmployeeCompensationConfig {
  EmployeeCompensationConfig._();

  static const String allFilter = 'All';
  static const int pageSize = 10;

  static const List<String> currencies = ['USD (\$)', 'EUR (€)', 'GBP (£)'];

  static const List<EmployeeCompensationTableRowData> mockRows = [
    EmployeeCompensationTableRowData(
      employeeName: 'Sarah Johnson',
      employeeId: 'EMP-2024-1234',
      employeeGuid: 'EMP-2024-1234',
      planGuid: '',
      department: 'Engineering',
      region: 'North America',
      position: 'Senior Software Engineer',
      compensationPlan: '2026 Executive Compensation Plan',
      salaryStructure: 'Executive Salary Structure',
      grade: 'E3',
      baseSalary: 8500,
      allowances: 2875,
      benefits: 500,
      status: 'Active',
    ),
    EmployeeCompensationTableRowData(
      employeeName: 'Michael Chen',
      employeeId: 'EMP-2024-1156',
      employeeGuid: 'EMP-2024-1156',
      planGuid: '',
      department: 'Engineering',
      region: 'Asia Pacific',
      position: 'Lead Developer',
      compensationPlan: 'Technology Department Plan',
      salaryStructure: 'Staff Salary Structure',
      grade: 'E4',
      baseSalary: 10500,
      allowances: 3400,
      benefits: 750,
      status: 'Active',
    ),
    EmployeeCompensationTableRowData(
      employeeName: 'Emily Rodriguez',
      employeeId: 'EMP-2024-0987',
      employeeGuid: 'EMP-2024-0987',
      planGuid: '',
      department: 'Sales',
      region: 'Europe',
      position: 'Sales Manager',
      compensationPlan: 'Sales Team Compensation',
      salaryStructure: 'Manager Salary Structure',
      grade: 'M2',
      baseSalary: 9000,
      allowances: 3100,
      benefits: 600,
      status: 'Active',
    ),
    EmployeeCompensationTableRowData(
      employeeName: 'David Kim',
      employeeId: 'EMP-2024-2341',
      employeeGuid: 'EMP-2024-2341',
      planGuid: '',
      department: 'Finance',
      region: 'Asia Pacific',
      position: 'Financial Analyst',
      compensationPlan: 'Standard Salary Structure 2026',
      salaryStructure: 'Manager Salary Structure',
      grade: 'E2',
      baseSalary: 7000,
      allowances: 2200,
      benefits: 400,
      status: 'Active',
    ),
    EmployeeCompensationTableRowData(
      employeeName: 'Jennifer Martinez',
      employeeId: 'EMP-2024-3456',
      employeeGuid: 'EMP-2024-3456',
      planGuid: '',
      department: 'HR',
      region: 'Latin America',
      position: 'HR Manager',
      compensationPlan: 'Standard Salary Structure 2026',
      salaryStructure: 'Manager Salary Structure',
      grade: 'M2',
      baseSalary: 8800,
      allowances: 2900,
      benefits: 650,
      status: 'Active',
    ),
    EmployeeCompensationTableRowData(
      employeeName: 'Robert Anderson',
      employeeId: 'EMP-2024-4567',
      employeeGuid: 'EMP-2024-4567',
      planGuid: '',
      department: 'Engineering',
      region: 'North America',
      position: 'Software Engineer',
      compensationPlan: 'Technology Department Plan',
      salaryStructure: 'Staff Salary Structure',
      grade: 'E2',
      baseSalary: 6800,
      allowances: 2150,
      benefits: 400,
      status: 'Active',
    ),
    EmployeeCompensationTableRowData(
      employeeName: 'Lisa Thompson',
      employeeId: 'EMP-2024-5678',
      employeeGuid: 'EMP-2024-5678',
      planGuid: '',
      department: 'Marketing',
      region: 'Europe',
      position: 'Marketing Director',
      compensationPlan: '2026 Executive Compensation Plan',
      salaryStructure: 'Executive Salary Structure',
      grade: 'M3',
      baseSalary: 11500,
      allowances: 3800,
      benefits: 850,
      status: 'Active',
    ),
    EmployeeCompensationTableRowData(
      employeeName: 'James Wilson',
      employeeId: 'EMP-2024-6789',
      employeeGuid: 'EMP-2024-6789',
      planGuid: '',
      department: 'Operations',
      region: 'North America',
      position: 'Operations Manager',
      compensationPlan: 'Standard Salary Structure 2026',
      salaryStructure: 'Manager Salary Structure',
      grade: 'M2',
      baseSalary: 9200,
      allowances: 3050,
      benefits: 600,
      status: 'Active',
    ),
    EmployeeCompensationTableRowData(
      employeeName: 'Maria Garcia',
      employeeId: 'EMP-2024-7890',
      employeeGuid: 'EMP-2024-7890',
      planGuid: '',
      department: 'Sales',
      region: 'Latin America',
      position: 'Senior Sales Executive',
      compensationPlan: 'Sales Team Compensation',
      salaryStructure: 'Manager Salary Structure',
      grade: 'E3',
      baseSalary: 8000,
      allowances: 2600,
      benefits: 500,
      status: 'Active',
    ),
    EmployeeCompensationTableRowData(
      employeeName: 'William Brown',
      employeeId: 'EMP-2024-8901',
      employeeGuid: 'EMP-2024-8901',
      planGuid: '',
      department: 'IT',
      region: 'Europe',
      position: 'IT Manager',
      compensationPlan: 'Technology Department Plan',
      salaryStructure: 'Manager Salary Structure',
      grade: 'M2',
      baseSalary: 9500,
      allowances: 3200,
      benefits: 700,
      status: 'Active',
    ),
    EmployeeCompensationTableRowData(
      employeeName: 'Olivia Taylor',
      employeeId: 'EMP-2024-9012',
      employeeGuid: 'EMP-2024-9012',
      planGuid: '',
      department: 'Finance',
      region: 'North America',
      position: 'Compensation Analyst',
      compensationPlan: 'Finance Leadership Plan',
      salaryStructure: 'Professional Salary Structure',
      grade: 'E2',
      baseSalary: 7600,
      allowances: 2100,
      benefits: 450,
      status: 'Active',
    ),
    EmployeeCompensationTableRowData(
      employeeName: 'Daniel Lee',
      employeeId: 'EMP-2024-9134',
      employeeGuid: 'EMP-2024-9134',
      planGuid: '',
      department: 'Operations',
      region: 'Asia Pacific',
      position: 'Operations Supervisor',
      compensationPlan: 'Operations Performance Plan',
      salaryStructure: 'Supervisor Salary Structure',
      grade: 'E3',
      baseSalary: 8400,
      allowances: 2450,
      benefits: 550,
      status: 'Active',
    ),
  ];
}
